### ISSUE TITLE
字体不清晰

### ISSUE THREAD

**Issue by yingfengchen** [XXllXX/PrintTemplate#11]
你好，大神  利用模板生成的PDF  出来后字体不清晰  打印出来很模糊 ，有没有好的办法啊， 宋体、黑体效果都不是很理想

**Comment by yingfengchen** [comment]
![image](https://user-images.githubusercontent.com/20177121/122395897-0a5a1d80-cfaa-11eb-99c1-c613d3b7cc48.png)

**Comment by yingfengchen** [comment]
![image](https://user-images.githubusercontent.com/20177121/122396005-22ca3800-cfaa-11eb-8f35-189055e846a3.png)

**Comment by XXllXX** [comment]
试过设置字体宽度吗

**Comment by XXllXX** [comment]
1.2.8版本已解决
