### ISSUE TITLE
错误  Error: Supplied data is not a JPEG

### ISSUE THREAD

**Issue by HuMiaoMonea** [XXllXX/PrintTemplate#14]
Error: Supplied data is not a JPEG

![image](https://user-images.githubusercontent.com/35440997/152798759-5e6225f9-075a-4ab8-ac47-a282ce829ee1.png)

**Comment by liangfans** [comment]
您好，请问您后面有解决这个问题嘛

**Comment by XXllXX** [comment]
最新版本1.2.7解决了
