### ISSUE TITLE
字体设置无效

### ISSUE THREAD

**Issue by Rikhard-Dong** [XXllXX/PrintTemplate#2]
![image](https://user-images.githubusercontent.com/22675968/79624426-1bb05b80-8154-11ea-9ea9-d5d5e46b8969.png)
![image](https://user-images.githubusercontent.com/22675968/79624437-2965e100-8154-11ea-9b8b-6f6b7dcf5c5a.png)
字体无论设置成什么都不会有变化?

**Comment by XXllXX** [comment]
非常感谢
------------------------------------------
已经修复并发布

**Comment by Rikhard-Dong** [comment]
感谢
