### ISSUE TITLE
生成pdf大小和设置的大小不一致

### ISSUE THREAD

**Issue by Niue** [XXllXX/PrintTemplate#5]
生成pdf大小和设置的大小不一致，导致打印pdf不对

**Comment by XXllXX** [comment]
请确保使用最新版本 1.2.2
如果还是有问题可以把 size 配置和pdf 截图发出来

**Comment by Niue** [comment]
<img width="1601" alt="WeChatf52b0f49676c323345fed4bc380ad22c" src="https://user-images.githubusercontent.com/6396878/101557525-2d52b600-39f8-11eb-8bbf-a8d1cd423bde.png">
<img width="480" alt="WeChat7a915a58d11a3ad95a53cb6134766ea4" src="https://user-images.githubusercontent.com/6396878/101557533-304da680-39f8-11eb-8390-a28a80ed471c.png">
<img width="1597" alt="WeChat7a203e76a75f636f9af076eb84608c5f" src="https://user-images.githubusercontent.com/6396878/101557554-36dc1e00-39f8-11eb-830b-3a50deac04a9.png">
<img width="444" alt="WeChate363babd4a49c47b7b84c1b5fe62e8d6" src="https://user-images.githubusercontent.com/6396878/101557560-38a5e180-39f8-11eb-9ba0-31383a299841.png">
设置A4的大小，pdf怎么那么大呢

**Comment by Niue** [comment]
<img width="1597" alt="WeChat7a203e76a75f636f9af076eb84608c5f" src="https://user-images.githubusercontent.com/6396878/101557813-b538c000-39f8-11eb-92f9-550d2c895426.png">
<img width="444" alt="WeChate363babd4a49c47b7b84c1b5fe62e8d6" src="https://user-images.githubusercontent.com/6396878/101557832-c1248200-39f8-11eb-8572-283bc83b1dd4.png">
<img width="1601" alt="WeChatf52b0f49676c323345fed4bc380ad22c" src="https://user-images.githubusercontent.com/6396878/101557855-caadea00-39f8-11eb-8b3c-ed0e447ece90.png">
<img width="480" alt="WeChat7a915a58d11a3ad95a53cb6134766ea4" src="https://user-images.githubusercontent.com/6396878/101557907-e6b18b80-39f8-11eb-9136-ecd82a276f07.png">
设置成A4大小，生成的pdf怎么那么大呢

**Comment by XXllXX** [comment]
A4 应该是 size:[210,297]     例子上 221,291 是错误的
生成的就是那么大 ，例子上的宽是76, A4是它的2.7倍大小 ，高度也是2倍左右
