### ISSUE TITLE
在得力标签打印机模板打印出来文字不清楚,请问有什么办法

### ISSUE THREAD

**Issue by gengsende** [XXllXX/PrintTemplate#7]
在得力标签打印机模板打印出来文字不清楚,请问您碰到过这种情况吗?

**Comment by XXllXX** [comment]
生成的pdf页面清楚吗，如果清楚的话就是打印机设置的问题

**Comment by yingfengchen** [comment]
我也遇到了  大神  生成的PDF是清楚地  但是打印出来就是很模糊  改变字体也不行，求帮助
